# Site settings
title: Origami.js
email: rapha850@gmail.com
description: Official website origami.js
baseurl: /
url: 0.0.0.0:4000
domain: origamijs.com

# Downlod Info
downloadLink: https://github.com/raphamorim/origami.js/archive/master.zip
downloadVersion: "0.5v"

# Aditional Info
contributeLink: https://github.com/raphamorim/origami.js/issues
repoUrl: https://github.com/raphamorim/origami.js

# Build settings
markdown: kramdown

collections:
  docs:
    output: true
    permalink: /docs/:path/

sass:
  sass_dir: assets/stylesheet
